### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005)

### ISSUE THREAD

**Issue by kungfux** [kungfux/rqs#5]
To reproduce the problem you need:
1. Prepare new database using TestData;
2. Start the server and navigate to search page via Browser;
3. Search for "FR1-10";
4. Press and hold F5 on the keyboard to refresh the page multiple times (several seconds).

Exception stack:
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at WebQA.Logic.AsynchronousSocketListener.AcceptCallback(IAsyncResult ar) in AsynchronousSocketListener.cs:line 112
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CaptureOrComplete(ExecutionContext& cachedContext, Boolean returnContext)
   at System.Net.ContextAwareResult.FinishPostingAsyncOp(CallbackClosure& closure)
   at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
   at WebQA.Logic.AsynchronousSocketListener.StartListening() in AsynchronousSocketListener.cs:line 85

**Comment by kungfux** [comment]
The issue will be fixed by switching the app to new fuse web server.
